import "./globals.css";
import type { Metadata } from "next";
import { Inter, Work_Sans } from "next/font/google";
import QueryProvider from "@/providers/queryProvider";

const worksans = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // manifest: "/manifest.json",
  // icons: { apple: "/icon.png" },
  // themeColor: "#fff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <QueryProvider>
      <html lang="en">
        <body className={worksans.className}>{children}</body>
      </html>
    </QueryProvider>
  );
}
